Repository gazebosim/gz-gui, pull requests merged in 2020-05, with the labels that each got.

#57 [ign-gui3] Workflow updates
  .github/CODEOWNERS
  .github/ci-bionic/after_make.sh
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  bitbucket-pipelines.yml
  codecov.yml
Labels: 🏰 citadel

#56 [ign-gui2] Workflow updates
  .github/CODEOWNERS
  .github/ci-bionic/after_make.sh
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  bitbucket-pipelines.yml
  codecov.yml
Labels: 📜 blueprint

#60 Close plugin menu after a plugin has been added
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🔮 dome

#62 Add color palette to plugin settings to change background color
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
Labels: enhancement, 🔮 dome

#59 [master] Workflow updates
  .github/ci-bionic/dependencies.yaml
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  bitbucket-pipelines.yml
  codecov.yml
Labels: 🔮 dome

#64 Move each plugin to its own directory
  CMakeLists.txt
  include/ignition/gui/CMakeLists.txt
  include/ignition/gui/plugins/CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/Requester.cc
  src/plugins/Requester_TEST.cc
  src/plugins/Responder.cc
  src/plugins/Responder_TEST.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/grid_3d/Grid3D.qrc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/image_display/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/image_display/ImageDisplay.qrc
  src/plugins/image_display/ImageDisplay_TEST.cc
  src/plugins/publisher/CMakeLists.txt
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher.hh
  src/plugins/publisher/Publisher.qml
  src/plugins/publisher/Publisher.qrc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D.qrc
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho.qrc
  src/plugins/topic_echo/TopicEcho_TEST.cc
  src/plugins/world_control/CMakeLists.txt
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl.qrc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/CMakeLists.txt
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats.qrc
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: enhancement, 🔮 dome
