Repository gazebosim/gz-gui, pull requests merged in 2020-09, with the labels that each got.

#119 ⬆️ 3.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#120 2.3.3 release prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#115 Plotting Header time
  .github/workflows/ci.yml
  include/ignition/gui/PlottingInterface.hh
  include/ignition/gui/qml/Chart.qml
  include/ignition/gui/qml/PlottingInterface.qml
  src/PlottingInterface.cc
  src/PlottingInterface_TEST.cc
Labels: beta, enhancement, 🔮 dome

#116 Using std::chrono instead of common::Time
  .github/ci-bionic/after_make.sh
  .github/ci-bionic/dependencies.yaml
  CMakeLists.txt
  Migration.md
  include/ignition/gui/Conversions.hh
  src/Conversions_TEST.cc
  src/plugins/world_stats/WorldStats.cc
Labels: beta, enhancement, needs upstream release, 🔮 dome

#124 Fix Plotting Crash
  include/ignition/gui/PlottingInterface.hh
  src/PlottingInterface.cc
  src/plugins/plotting/TransportPlotting.cc
Labels: beta, bug, 🔮 dome

#125 Small tweaks to the plot plugin
  include/ignition/gui/qml/Chart.qml
  src/plugins/plotting/TransportPlotting.cc
Labels: beta, 🔮 dome

#126 Fix qt5 anchor warnings
  src/plugins/world_control/WorldControl.qml
Labels: beta, bug, 🔮 dome

#128 Publish plugin API docs
  CMakeLists.txt
  tutorials/03_plugins.md
Labels: documentation, 🏰 citadel

#130 Updated ign-gui 06_example.md
  tutorials/06_example.md
Labels: documentation, 🔮 dome

#127 Updates to README and installation
  CONTRIBUTING.md
  README.md
  api.md.in
  tutorials/01_install.md
Labels: documentation, macOS, 🔮 dome

#132 some gui tutorial tweaks
  examples/config/layout.config
  examples/plugin/hello_plugin/HelloPlugin.qml
  src/plugins/world_control/WorldControl.qml
  tutorials/02_commandline.md
  tutorials/05_style.md
Labels: 🏰 citadel

#133 ⬆️ 4.0.0: Dome stable release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome
