Repository gazebosim/gz-gui, pull requests merged in 2020-12, with the labels that each got.

#150 Suggestions to #148
  include/ignition/gui/GuiEvents.hh
  src/CMakeLists.txt
  src/GuiEvents_TEST.cc
Labels: 🏰 citadel

#148 Add gazebo gui events
  include/ignition/gui/GuiEvents.hh
  src/CMakeLists.txt
  src/GuiEvents_TEST.cc
Labels: 🏰 citadel

#153 Change deprecated Qt::MidButton
  src/Conversions.cc
Labels: macOS, 🏰 citadel

#154 Add right mouse events and tests
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents_TEST.cc
Labels: 🏰 citadel

#155 Avoid crash on MacOS
  src/plugins/scene3d/Scene3D.cc
Labels: bug, macOS, 🔮 dome

#152 3 ➡️ 4
  Changelog.md
  include/ignition/gui/GuiEvents.hh
  src/CMakeLists.txt
  src/Conversions.cc
  src/GuiEvents_TEST.cc
Labels: 🔮 dome

#156 4 ➡️ 5
  Changelog.md
  include/ignition/gui/GuiEvents.hh
  src/CMakeLists.txt
  src/Conversions.cc
  src/GuiEvents_TEST.cc
  src/plugins/scene3d/Scene3D.cc
Labels: 🏢 edifice

#157 Fix codecheck
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/topic_viewer/TopicViewer.cc
Labels: 🏰 citadel

#158 3 ➡️ 4
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/topic_viewer/TopicViewer.cc
Labels: 🔮 dome

#159 ⬆️ 4.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#160 4 ➡️ 5
  Changelog.md
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/topic_viewer/TopicViewer.cc
Labels: 🏢 edifice
