Repository gazebosim/gz-gui, pull requests merged in 2020-11, with the labels that each got.

#141 Bump in edifice: ign-rendering5
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🏢 edifice

#144 Resolve updated codecheck issues
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
Labels: 📜 blueprint

#146 2 to 3
  Changelog.md
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
Labels: 🏰 citadel

#143 3 ➡️ 4
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  CMakeLists.txt
  Changelog.md
  examples/config/layout.config
  examples/plugin/hello_plugin/HelloPlugin.qml
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnRulers.qml
  include/ignition/gui/qml/PluginMenu.qml
  src/Application.cc
  src/Plugin.cc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_stats/WorldStats.cc
  test/integration/Examples_TEST.cc
  tutorials/02_commandline.md
  tutorials/03_plugins.md
  tutorials/05_style.md
Labels: 🔮 dome
