Repository gazebosim/gz-gui, pull requests merged in 2020-07, with the labels that each got.

#88 Fixed ImageDisplay in Ubuntu 20.04
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
Labels: bug, 🔮 dome

#65 Re-enable publisher test
  src/plugins/CMakeLists.txt
  src/plugins/publisher/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
Labels: tests, 🔮 dome

#96 Add shift + drag to rotate camera
  src/plugins/scene3d/Scene3D.cc
Labels: 📜 blueprint

#92 Update deps for Dome: use msgs6, transport9
  .github/ci-bionic/after_make.sh
  .github/workflows/ci-bionic.yml
  CMakeLists.txt
  README.md
Labels: 🔮 dome

#97 Scroll bar adjustment
  include/ignition/gui/qml/IgnSplit.qml
Labels: bug, 📜 blueprint
