Repository gazebosim/gz-gui, pull requests merged in 2020-06, with the labels that each got.

#71 Sort GUI plugins alphabetically
  src/MainWindow.cc
Labels: enhancement, 🔮 dome

#70 Add render event
  include/ignition/gui/GuiEvents.hh
  src/plugins/scene3d/Scene3D.cc
Labels: enhancement, 🔮 dome

#72 master ➡️ 2
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
  include/ignition/gui/qml/PluginMenu.qml
  src/MainWindow.cc
Labels: 📜 blueprint

#78 Resize undocked plugins by dragging corners
  include/ignition/gui/qml/IgnRulers.qml
Labels: enhancement, 📜 blueprint

#82 4 ➡️ 2
  CMakeLists.txt
  include/ignition/gui/CMakeLists.txt
  include/ignition/gui/plugins/CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/Requester.cc
  src/plugins/Requester_TEST.cc
  src/plugins/Responder.cc
  src/plugins/Responder_TEST.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/grid_3d/Grid3D.qrc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/image_display/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/image_display/ImageDisplay.qrc
  src/plugins/image_display/ImageDisplay_TEST.cc
  src/plugins/publisher/CMakeLists.txt
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher.hh
  src/plugins/publisher/Publisher.qml
  src/plugins/publisher/Publisher.qrc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D.qrc
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho.qrc
  src/plugins/topic_echo/TopicEcho_TEST.cc
  src/plugins/world_control/CMakeLists.txt
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl.qrc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/CMakeLists.txt
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats.qrc
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: 📜 blueprint

#79 2 ➡️ 3
  CMakeLists.txt
  include/ignition/gui/CMakeLists.txt
  include/ignition/gui/plugins/CMakeLists.txt
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
  include/ignition/gui/qml/IgnRulers.qml
  include/ignition/gui/qml/PluginMenu.qml
  src/MainWindow.cc
  src/plugins/CMakeLists.txt
  src/plugins/Requester.cc
  src/plugins/Requester_TEST.cc
  src/plugins/Responder.cc
  src/plugins/Responder_TEST.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/grid_3d/Grid3D.qrc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/image_display/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/image_display/ImageDisplay.qrc
  src/plugins/image_display/ImageDisplay_TEST.cc
  src/plugins/publisher/CMakeLists.txt
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher.hh
  src/plugins/publisher/Publisher.qml
  src/plugins/publisher/Publisher.qrc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D.qrc
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho.qrc
  src/plugins/topic_echo/TopicEcho_TEST.cc
  src/plugins/world_control/CMakeLists.txt
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl.qrc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/CMakeLists.txt
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats.qrc
  src/plugins/world_stats/WorldStats_TEST.cc
  tutorials/03_plugins.md
Labels: 🏰 citadel

#83 ⬆️ Bump 2.2
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#81 KeyPublisher
  examples/config/keypublisher.config
  src/plugins/CMakeLists.txt
  src/plugins/key_publisher/CMakeLists.txt
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/key_publisher/KeyPublisher.qml
  src/plugins/key_publisher/KeyPublisher.qrc
  tutorials/03_plugins.md
Labels: enhancement, 🏰 citadel

#86 ⬆️ Bump 3.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#85 Fixed left menu events
  examples/standalone/custom_drawer/CustomDrawer.qml
  include/ignition/gui/qml/SideDrawer.qml
Labels: bug, 🔮 dome
