Repository gazebosim/gz-gui, pull requests merged in 2020-10, with the labels that each got.

#135 Floating and standalone plugins respect minimum dimensions
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnRulers.qml
  src/Application.cc
  src/Plugin.cc
Labels: 🏰 citadel

#134 Add scrollable indicator for plugin menu
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🏰 citadel

#136 Add qml-module-qtcharts dependency
  .github/ci/packages.apt
Labels: 🔮 dome

#140 Re-enable image.config test
  test/integration/Examples_TEST.cc
Labels: tests, 🏰 citadel

#139 Improve fork experience
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel
