Repository gazebosim/gz-gui, pull requests merged in 2020-08, with the labels that each got.

#84 Minimize GUI Plugins
  examples/config/plugin_params.config
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
  include/ignition/gui/qml/IgnSplit.qml
Labels: 📜 blueprint

#99 Fix Grid3D plugin
  src/plugins/grid_3d/Grid3D.qml
Labels: bug, 📜 blueprint

#98 Fix tests on actions
  .github/ci-bionic/after_make.sh
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  src/ign_TEST.cc
  src/plugins/CMakeLists.txt
Labels: 📜 blueprint

#100 2 ➡️ 3
  .github/ci-bionic/after_make.sh
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  examples/config/plugin_params.config
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnCardSettings.qml
  include/ignition/gui/qml/IgnSplit.qml
  src/ign_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/scene3d/Scene3D.cc
Labels: 🏰 citadel

#69 Transport Topics Plugin
  src/plugins/CMakeLists.txt
  src/plugins/topic_viewer/CMakeLists.txt
  src/plugins/topic_viewer/TopicViewer.cc
  src/plugins/topic_viewer/TopicViewer.hh
  src/plugins/topic_viewer/TopicViewer.qml
  src/plugins/topic_viewer/TopicViewer.qrc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/topic_viewer/minus.png
  src/plugins/topic_viewer/plottable_icon.svg
  src/plugins/topic_viewer/plus.png
Labels: enhancement, 🔮 dome

#103 Disable TopicViewer_TEST on Windows and macOS
  src/plugins/topic_viewer/TopicViewer_TEST.cc
Labels: Windows, macOS, tests, 🔮 dome

#76 Disable failing tests
  examples/plugin/hello_plugin/HelloPlugin.hh
  src/Application_TEST.cc
  src/Helpers_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin_TEST.cc
  src/ign_TEST.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
Labels: 📜 blueprint

#104 Use world name in default topics
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/IgnCard.qml
  src/Helpers.cc
  src/Helpers_TEST.cc
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
Labels: 📜 blueprint

#105 ⬆️ 2.3.0
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#107 Fix running plugins with bad world name
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: bug, 📜 blueprint

#108 ⬆️ 2.3.1
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#110 Revert pull request #107 due to breaking changes in Blueprint
  CMakeLists.txt
  Changelog.md
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: 📜 blueprint

#111 Fix running plugins with bad-er world name
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: bug, 📜 blueprint

#106 Removed repeated installation instructions
  README.md
  tutorials/01_install.md
Labels: documentation, 🔮 dome

#109 2 ➡️ 3
  .github/workflows/ci.yml
  Changelog.md
  examples/plugin/hello_plugin/HelloPlugin.hh
  include/ignition/gui/Application.hh
  include/ignition/gui/Conversions.hh
  include/ignition/gui/Dialog.hh
  include/ignition/gui/Helpers.hh
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/Plugin.hh
  include/ignition/gui/qml/IgnCard.qml
  src/Application_TEST.cc
  src/CMakeLists.txt
  src/Helpers.cc
  src/Helpers_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats_TEST.cc
  test/gtest/src/gtest.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
Labels: 🏰 citadel

#89 Plotting interface
  .github/ci/packages.apt
  include/ignition/gui/CMakeLists.txt
  include/ignition/gui/PlottingInterface.hh
  include/ignition/gui/qml/Chart.qml
  include/ignition/gui/qml/PlottingInterface.qml
  include/ignition/gui/qml/images/export_icon.png
  include/ignition/gui/resources.qrc
  src/CMakeLists.txt
  src/PlottingInterface.cc
  src/PlottingInterface_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/plotting/CMakeLists.txt
  src/plugins/plotting/TransportPlotting.cc
  src/plugins/plotting/TransportPlotting.hh
  src/plugins/plotting/TransportPlotting.qml
  src/plugins/plotting/TransportPlotting.qrc
Labels: enhancement, 🔮 dome

#117 3 ➡️ 4
  .github/workflows/ci.yml
  Changelog.md
  examples/config/layout.config
  examples/plugin/hello_plugin/HelloPlugin.hh
  include/ignition/gui/Application.hh
  include/ignition/gui/Conversions.hh
  include/ignition/gui/Dialog.hh
  include/ignition/gui/Helpers.hh
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/Plugin.hh
  src/Application_TEST.cc
  src/CMakeLists.txt
  src/Helpers.cc
  src/Helpers_TEST.cc
  src/MainWindow_TEST.cc
  src/PlottingInterface_TEST.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_viewer/TopicViewer.cc
  src/plugins/topic_viewer/TopicViewer.hh
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats_TEST.cc
  test/gtest/src/gtest.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
Labels: 🔮 dome
