Repository gazebosim/gz-gui, pull requests merged in 2021-11, with the labels that each got.

#309 Set near/far camera clipping distance
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  test/integration/minimal_scene.cc
Labels: 🏯 fortress, 🌱 garden

#311 5 ➡️ 6
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  include/ignition/gui/Application.hh
  include/ignition/gui/GuiEvents.hh
  include/ignition/gui/PlottingInterface.hh
  include/ignition/gui/Plugin.hh
  src/plugins/grid_config/GridConfig.hh
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/minimal_scene/MinimalScene.hh
  tutorials/03_plugins.md
Labels: 🏯 fortress, 🌱 garden

#306 Support emitting an event on play/pause/step
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/world_control/CMakeLists.txt
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControlEventListener.cc
  src/plugins/world_control/WorldControlEventListener.hh
  src/plugins/world_control/WorldControl_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#312 Prepare for 6.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress, 🌱 garden

#272 Added log storing for ign-gui
  src/ign.cc
  src/ign_TEST.cc
  tutorials/02_commandline.md
Labels: 🏰 citadel

#316 Merge 6 -> 7
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  include/ignition/gui/Application.hh
  include/ignition/gui/GuiEvents.hh
  include/ignition/gui/PlottingInterface.hh
  include/ignition/gui/Plugin.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/world_control/CMakeLists.txt
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControlEventListener.cc
  src/plugins/world_control/WorldControlEventListener.hh
  src/plugins/world_control/WorldControl_TEST.cc
  test/integration/minimal_scene.cc
  tutorials/03_plugins.md
Labels: 🌱 garden

#315 Don't crash if a plugin has invalid QML
  src/Application.cc
  src/Application_TEST.cc
  test/plugins/CMakeLists.txt
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestInvalidQmlPlugin.hh
  test/plugins/TestInvalidQmlPlugin.qml
  test/plugins/TestInvalidQmlPlugin.qrc
Labels: bug, 🏰 citadel

#317 Set marker point size from message
  src/plugins/marker_manager/MarkerManager.cc
Labels: enhancement, 🏯 fortress

#321 Don't set visual scale for point markers
  src/plugins/marker_manager/MarkerManager.cc
Labels: bug, 🏯 fortress
