Repository gazebosim/gz-gui, pull requests merged in 2021-07, with the labels that each got.

#244 Fixed tests
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/Examples_TEST.cc
  test/integration/scene3d.cc
Labels: bug, tests, 🏰 citadel

#221 Split transport scene manager into a plugin outside Scene3D
  CMakeLists.txt
  Migration.md
  examples/config/scene3d.config
  examples/standalone/scene_provider/CMakeLists.txt
  examples/standalone/scene_provider/README.md
  examples/standalone/scene_provider/scene_provider.cc
  src/plugins/CMakeLists.txt
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalScene.qml
  src/plugins/minimal_scene/MinimalScene.qrc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/transport_scene_manager/CMakeLists.txt
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/transport_scene_manager/TransportSceneManager.hh
  src/plugins/transport_scene_manager/TransportSceneManager.qml
  src/plugins/transport_scene_manager/TransportSceneManager.qrc
  test/integration/minimal_scene.cc
  test/integration/transport_scene_manager.cc
  tutorials.md.in
  tutorials/scene.md
Labels: 🏯 fortress

#226 Added camera tracking
  CMakeLists.txt
  examples/config/scene3d.config
  examples/standalone/scene_provider/README.md
  src/plugins/CMakeLists.txt
  src/plugins/camera_tracking/CMakeLists.txt
  src/plugins/camera_tracking/CameraTracking.cc
  src/plugins/camera_tracking/CameraTracking.hh
  src/plugins/camera_tracking/CameraTracking.qml
  src/plugins/camera_tracking/CameraTracking.qrc
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  test/integration/camera_tracking.cc
Labels: 🏯 fortress

#249 Fix plugin added signal, add PluginByName
  Migration.md
  include/ignition/gui/Application.hh
  src/Application.cc
  src/Application_TEST.cc
Labels: bug, 🏰 citadel

#251 Fix codeowners
  .github/CODEOWNERS
Labels: 🏰 citadel

#252 🎈 3.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#254 Remove windows warnings in CameraTracking
  test/integration/camera_tracking.cc
Labels: enhancement, 🏯 fortress

#253 PIMPL GUI events
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
Labels: 🏯 fortress

#245 New teleop plugin implementation.
  src/plugins/CMakeLists.txt
  src/plugins/teleop/CMakeLists.txt
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop.qrc
  src/plugins/teleop/Teleop_TEST.cc
Labels: 🏰 citadel

#247 Added MarkerManager Plugin
  examples/config/scene3d.config
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/marker/README.md
  examples/standalone/marker/marker.cc
  examples/standalone/scene_provider/scene_provider.cc
  src/plugins/CMakeLists.txt
  src/plugins/marker_manager/CMakeLists.txt
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/marker_manager/MarkerManager.hh
  src/plugins/marker_manager/MarkerManager.qml
  src/plugins/marker_manager/MarkerManager.qrc
  test/integration/marker_manager.cc
Labels: 🏯 fortress

#256 3 ➡️ 4
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  Migration.md
  include/ignition/gui/Application.hh
  src/Application.cc
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/plugins/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/teleop/CMakeLists.txt
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop.qrc
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/Examples_TEST.cc
  test/integration/scene3d.cc
Labels: 🔮 dome

#257 4 ➡️ 5
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  Migration.md
  include/ignition/gui/Application.hh
  src/Application.cc
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/plugins/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/teleop/CMakeLists.txt
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop.qrc
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/Examples_TEST.cc
  test/integration/scene3d.cc
Labels: 🏢 edifice

#231 Added Interactive view control plugin
  examples/config/scene3d.config
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/interactive_view_control/CMakeLists.txt
  src/plugins/interactive_view_control/InteractiveViewControl.cc
  src/plugins/interactive_view_control/InteractiveViewControl.hh
  src/plugins/interactive_view_control/InteractiveViewControl.qml
  src/plugins/interactive_view_control/InteractiveViewControl.qrc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
Labels: 🏯 fortress

#258 5 ➡️ 6
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  Migration.md
  include/ignition/gui/Application.hh
  src/Application.cc
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/plugins/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/teleop/CMakeLists.txt
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop.qrc
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/Examples_TEST.cc
  test/integration/scene3d.cc
Labels: 🏯 fortress

#259 🎈 4.5.0
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🔮 dome

#260 4 to 5
  Changelog.md
  Migration.md
Labels: 🏢 edifice

#261 5.2.0
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏢 edifice
