Repository gazebosim/gz-gui, pull requests merged in 2021-02, with the labels that each got.

#172 Make Grid3D plugin more flexible
  examples/config/scene3d.config
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
Labels: bug, 🏰 citadel

#174 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#175 Better error messages when component can't be loaded
  src/Plugin.cc
Labels: enhancement, 🏰 citadel

#176 Visualize single channel 8 bit image data
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
Labels: 🔮 dome

#178 4.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#179 Fix version number
  CMakeLists.txt
Labels: 🔮 dome

#173 Backport Publisher test from v4
  src/plugins/publisher/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
Labels: 🏰 citadel

#181 Remove issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#169 Bump in edifice: ign-common4
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: needs upstream release, 🏢 edifice

#184 👩‍🌾 Disable tests that initialize App on macOS: they're all flaky
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin_TEST.cc
Labels: bug, macOS, tests, 🔮 dome

#180 3 ➡️ 4
  README.md
  examples/config/scene3d.config
  src/Plugin.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  tutorials/01_install.md
Labels: 🔮 dome

#185 👩‍🌾 4 ➡️ 5
  Changelog.md
  README.md
  examples/config/scene3d.config
  src/Application_TEST.cc
  src/MainWindow_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/ign.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
  tutorials/01_install.md
Labels: 🏢 edifice
