Repository gazebosim/gz-gui, pull requests merged in 2021-05, with the labels that each got.

#219 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#222 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🏰 citadel

#223 Removed duplicated code with rendering::sceneFromFirstRenderEngine
  src/plugins/screenshot/Screenshot.cc
Labels: enhancement, needs upstream release, 🏰 citadel

#213 Emit more events from Scene3D
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D_TEST.cc
  test/CMakeLists.txt
  test/helpers/CMakeLists.txt
  test/helpers/TestHelper.cc
  test/helpers/TestHelper.hh
  test/integration/CMakeLists.txt
  test/integration/scene3d.cc
Labels: 🏰 citadel

#227 Avoid grid3D crash
  src/plugins/grid_3d/Grid3D.cc
Labels: bug, 🏰 citadel
