Repository gazebosim/gz-gui, pull requests merged in 2021-09, with the labels that each got.

#278 Add SpawnCloneFromName event
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
Labels: 🏯 fortress

#279 3 ➡️ 4
  bitbucket-pipelines.yml
  include/ignition/gui/qml/IgnSortFilterModel.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/PluginMenu.qml
  include/ignition/gui/qml/images/search.svg
  include/ignition/gui/resources.qrc
Labels: 🔮 dome, beta

#280 4 ➡️ 5
  bitbucket-pipelines.yml
  include/ignition/gui/qml/IgnSortFilterModel.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/PluginMenu.qml
  include/ignition/gui/qml/images/search.svg
  include/ignition/gui/resources.qrc
Labels: beta, 🏢 edifice

#281 5 ➡️ 6 (main)
  CMakeLists.txt
  Changelog.md
  Migration.md
  bitbucket-pipelines.yml
  include/ignition/gui/qml/IgnSortFilterModel.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/PluginMenu.qml
  include/ignition/gui/qml/images/search.svg
  include/ignition/gui/resources.qrc
Labels: beta, 🏯 fortress

#285 Fix race condition when rendering the UI
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
Labels: bug, beta, 🏯 fortress

#287 Fix memory leak in ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.cc
Labels: bug, 🔮 dome, performance

#282 Added drop event
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalScene.qml
Labels: beta, 🏯 fortress

#286 Fix render engine GUI name argument to be setted in the minimal scene
  include/ignition/gui/Helpers.hh
  include/ignition/gui/MainWindow.hh
  src/Helpers.cc
  src/Helpers_TEST.cc
  src/MainWindow.cc
  src/plugins/minimal_scene/MinimalScene.cc
  test/integration/marker_manager.cc
Labels: bug, beta, 🏯 fortress

#284 Fixed Right click press position
  src/plugins/minimal_scene/MinimalScene.cc
Labels: bug, beta, 🏯 fortress

#288 🎈 6.0.0~pre1
  Changelog.md
Labels: beta, 🏯 fortress

#292 Added winID to fix second windows in OGRE2.2
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/scene3d/Scene3D.cc
Labels: bug, needs upstream release, beta, 🏯 fortress
