Repository gazebosim/gz-gui, pull requests merged in 2021-12, with the labels that each got.

#322 Fix message display in TopicEcho
  src/plugins/topic_echo/TopicEcho.qml
Labels: bug, 🏯 fortress

#319 use qmldir to define QML module with IgnSpinBox
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/qmldir
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Helpers.cc
  src/plugins/teleop/Teleop.qml
Labels: 🏰 citadel

#325 Add PreRender event to MinimalScene
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/minimal_scene/MinimalScene.cc
  test/integration/minimal_scene.cc
  tutorials/scene.md
Labels: 🏯 fortress

#327 Bumps in garden : ci_matching_branch/bump_garden_ign-gui7
  .github/ci/packages.apt
  CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_provider/CMakeLists.txt
Labels: 🌱 garden

#326 Offer a way to disable warnings on marker manager
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/marker_manager/MarkerManager.hh
Labels: enhancement, 🏯 fortress

#329 Fix codecheck
  include/ignition/gui/Helpers.hh
Labels: 🏰 citadel

#328 3 ➡️ 4
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/qmldir
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Application_TEST.cc
  src/Helpers.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/teleop/Teleop.qml
  src/plugins/topic_echo/TopicEcho.qml
  test/plugins/CMakeLists.txt
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestInvalidQmlPlugin.hh
  test/plugins/TestInvalidQmlPlugin.qml
  test/plugins/TestInvalidQmlPlugin.qrc
  tutorials/02_commandline.md
Labels: 🔮 dome

#330 4 ➡️ 5
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/qmldir
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Application_TEST.cc
  src/Helpers.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/teleop/Teleop.qml
  src/plugins/topic_echo/TopicEcho.qml
  test/plugins/CMakeLists.txt
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestInvalidQmlPlugin.hh
  test/plugins/TestInvalidQmlPlugin.qml
  test/plugins/TestInvalidQmlPlugin.qrc
  tutorials/02_commandline.md
Labels: 🏢 edifice

#331 5 ➡️ 6
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/qmldir
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Application_TEST.cc
  src/Helpers.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/teleop/Teleop.qml
  src/plugins/topic_echo/TopicEcho.qml
  test/plugins/CMakeLists.txt
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestInvalidQmlPlugin.hh
  test/plugins/TestInvalidQmlPlugin.qml
  test/plugins/TestInvalidQmlPlugin.qrc
  tutorials/02_commandline.md
Labels: 🏯 fortress

#332 Fix codecheck
  src/plugins/marker_manager/MarkerManager.cc
Labels: 🏯 fortress

#324 Grid config: set values from startup and improve layout
  Migration.md
  examples/config/grid_config.config
  src/plugins/CMakeLists.txt
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/grid_3d/Grid3D.qrc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/grid_config/CMakeLists.txt
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/grid_config/GridConfig.qml
Labels: 🏯 fortress

#318 Set per-point color on markers
  examples/standalone/marker/marker.cc
  src/plugins/marker_manager/MarkerManager.cc
Labels: 🌱 garden

#333 6 ➡️ 7 (main)
  Migration.md
  examples/config/grid_config.config
  include/ignition/gui/GuiEvents.hh
  include/ignition/gui/Helpers.hh
  include/ignition/gui/qml/qmldir
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Application_TEST.cc
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/Helpers.cc
  src/ign.cc
  src/ign_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qrc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/grid_config/CMakeLists.txt
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/grid_config/GridConfig.qml
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/marker_manager/MarkerManager.hh
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/teleop/Teleop.qml
  src/plugins/topic_echo/TopicEcho.qml
  test/integration/minimal_scene.cc
  test/plugins/CMakeLists.txt
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestInvalidQmlPlugin.hh
  test/plugins/TestInvalidQmlPlugin.qml
  test/plugins/TestInvalidQmlPlugin.qrc
  tutorials/02_commandline.md
  tutorials/scene.md
Labels: 🌱 garden

#334 🎈6.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#340 🎈 4.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#343 Bumps in garden: depend on ign-math7 and ign-common5
  .github/ci/packages.apt
  CMakeLists.txt
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  include/ignition/gui/Conversions.hh
  src/plugins/scene3d/Scene3D.cc
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/world_control/WorldControl.cc
Labels: 🌱 garden
