Repository gazebosim/gz-gui, pull requests merged in 2021-06, with the labels that each got.

#225 Confirmation dialog when closing main window
  examples/config/layout.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  test/config/test.config
  tutorials/04_layout.md
Labels: enhancement, 🏰 citadel

#229 Fixed texture Id
  src/plugins/scene3d/Scene3D.cc
Labels: enhancement

#232 Update codeowners
  .github/CODEOWNERS
Labels: 🏰 citadel

#233 🎈 3.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#234 3 ➡️ 4
  .github/CODEOWNERS
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  examples/config/layout.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  test/CMakeLists.txt
  test/config/test.config
  test/helpers/CMakeLists.txt
  test/helpers/TestHelper.cc
  test/helpers/TestHelper.hh
  test/integration/CMakeLists.txt
  test/integration/scene3d.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
  tutorials/04_layout.md
Labels: 🔮 dome

#237 🎈 4.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#236 Moved tape measure and grid config from ign-gazebo to ign-gui
  src/plugins/CMakeLists.txt
  src/plugins/grid_config/CMakeLists.txt
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/grid_config/GridConfig.qml
  src/plugins/grid_config/GridConfig.qrc
  src/plugins/tape_measure/CMakeLists.txt
  src/plugins/tape_measure/TapeMeasure.cc
  src/plugins/tape_measure/TapeMeasure.hh
  src/plugins/tape_measure/TapeMeasure.qml
  src/plugins/tape_measure/TapeMeasure.qrc
  src/plugins/tape_measure/tape_measure.png
  src/plugins/tape_measure/trashcan.png
Labels: 🏯 fortress

#238 4 ➡️ 5
  .github/CODEOWNERS
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  examples/config/layout.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  test/CMakeLists.txt
  test/config/test.config
  test/helpers/CMakeLists.txt
  test/helpers/TestHelper.cc
  test/helpers/TestHelper.hh
  test/integration/CMakeLists.txt
  test/integration/scene3d.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
  tutorials/04_layout.md
Labels: 🏢 edifice

#240 Detect ign instead of using cmake module to check for ignition-tools
  CMakeLists.txt
Labels: 🏰 citadel

#241 🎈 5.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#242 Ahcorde/5 to main
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  examples/config/layout.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/plugins/grid_3d/CMakeLists.txt
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  test/CMakeLists.txt
  test/config/test.config
  test/helpers/CMakeLists.txt
  test/helpers/TestHelper.cc
  test/helpers/TestHelper.hh
  test/integration/CMakeLists.txt
  test/integration/scene3d.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
  tutorials/04_layout.md
Labels: 🏯 fortress

#243 Remove deprecations: tock
  include/ignition/gui/Conversions.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: 🏯 fortress

#228 Added Mouse Events
  include/ignition/gui/GuiEvents.hh
  src/CMakeLists.txt
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/scene3d/Scene3D.cc
  test/integration/scene3d.cc
Labels: 🏯 fortress

#246 Screenshot plugin fixed dbg message
  src/plugins/screenshot/Screenshot.cc
Labels: bug, 🏰 citadel

#224 Emit key events from Scene3D
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  test/integration/scene3d.cc
Labels: enhancement, 🏯 fortress
