Repository gazebosim/gz-gui, pull requests merged in 2021-08, with the labels that each got.

#264 Require ign-rendering 3.5
  CMakeLists.txt
Labels: 🏰 citadel

#266 Fix Doc Build Error
  CMakeLists.txt
Labels: 🏢 edifice

#268 Emit ignition gui key events in minimal scene3D
  include/ignition/gui/Conversions.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
Labels: 🏯 fortress

#273 Create new GuiEvent HoverOnScene
  include/ignition/gui/GuiEvents.hh
  src/GuiEvents.cc
  src/GuiEvents_TEST.cc
  src/plugins/minimal_scene/MinimalScene.cc
Labels: 🏯 fortress

#274 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel
