Repository gazebosim/gz-gui, pull requests merged in 2021-03, with the labels that each got.

#187 Master branch updates
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
  test/integration/ExamplesBuild_TEST.cc
  tutorials/01_install.md
  tutorials/05_style.md
Labels: 🏰 citadel

#170 Screenshot plugin
  CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.qml
  src/plugins/screenshot/CMakeLists.txt
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.hh
  src/plugins/screenshot/Screenshot.qml
  src/plugins/screenshot/Screenshot.qrc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/screenshot/folder.png
  src/plugins/screenshot/screenshot.png
  tutorials.md.in
  tutorials/06_example.md
  tutorials/08_screenshot.md
  tutorials/images/screenshot_button.png
  tutorials/images/screenshot_change_directory.png
  tutorials/images/screenshot_menu.png
  tutorials/images/screenshot_plugin.png
Labels: 🏰 citadel

#188 🎈 3.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#189 3 ➡️ 4
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  README.md
  bitbucket-pipelines.yml
  src/plugins/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.qml
  src/plugins/screenshot/CMakeLists.txt
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.hh
  src/plugins/screenshot/Screenshot.qml
  src/plugins/screenshot/Screenshot.qrc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/screenshot/folder.png
  src/plugins/screenshot/screenshot.png
  test/integration/ExamplesBuild_TEST.cc
  tutorials.md.in
  tutorials/01_install.md
  tutorials/05_style.md
  tutorials/06_example.md
  tutorials/08_screenshot.md
  tutorials/images/screenshot_button.png
  tutorials/images/screenshot_change_directory.png
  tutorials/images/screenshot_menu.png
  tutorials/images/screenshot_plugin.png
Labels: 🔮 dome

#190 🎈4.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#191 Scene3D: port mesh material fixes from ign-gazebo
  src/plugins/scene3d/Scene3D.cc
Labels: 🏰 citadel

#192 3 ➡️ 4 Forward port Scene3D mesh material fixes
  src/plugins/scene3d/Scene3D.cc
Labels: 🔮 dome

#193 Merge 4 ➡️ main
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  README.md
  bitbucket-pipelines.yml
  src/plugins/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.qml
  src/plugins/screenshot/CMakeLists.txt
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.hh
  src/plugins/screenshot/Screenshot.qml
  src/plugins/screenshot/Screenshot.qrc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/screenshot/folder.png
  src/plugins/screenshot/screenshot.png
  test/integration/ExamplesBuild_TEST.cc
  tutorials.md.in
  tutorials/01_install.md
  tutorials/05_style.md
  tutorials/06_example.md
  tutorials/08_screenshot.md
  tutorials/images/screenshot_button.png
  tutorials/images/screenshot_change_directory.png
  tutorials/images/screenshot_menu.png
  tutorials/images/screenshot_plugin.png
Labels: 🏢 edifice

#194 Improve the height of plugins in the right split
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnSplit.qml
  src/plugins/publisher/Publisher.qml
Labels: bug, 🏰 citadel

#195 Bump to 3.5.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#196 3 ➡️ 4
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnSplit.qml
  src/plugins/publisher/Publisher.qml
Labels: 🔮 dome

#197 4 ➡️ 5
  include/ignition/gui/qml/IgnCard.qml
  include/ignition/gui/qml/IgnSplit.qml
  src/plugins/publisher/Publisher.qml
Labels: beta, bug, 🏢 edifice

#199 🎈 5.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#202 Update README.md
  README.md
Labels: documentation, 🏢 edifice

#204 Edifice tutorial updates
  README.md
  examples/config/layout.config
  examples/config/scene3d.config
  tutorials/03_plugins.md
  tutorials/04_layout.md
  tutorials/05_style.md
  tutorials/07_config.md
Labels: documentation, 🏢 edifice

#205 🎈 5.0.0~pre2
  CMakeLists.txt
Labels: 🏢 edifice
