Repository gazebosim/gz-gui, pull requests merged in 2021-01, with the labels that each got.

#165 use default value of double ptr
  src/ign.cc
Labels: 🔮 dome

#164 Generate valid topics depending on world name
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
Labels: 🔮 dome

#166 ⬆️ 4.1.1
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#167 Bump in edifice: ign-msgs7, ign-transport10
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
Labels: 🏢 edifice

#168 Add Windows Installation
  README.md
  tutorials/01_install.md
Labels: 🏰 citadel
