Repository gazebosim/gz-gui, pull requests merged in 2022-11, with the labels that each got.

#477 Add key publisher test
  src/plugins/key_publisher/CMakeLists.txt
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/key_publisher/KeyPublisher_TEST.cc
Labels: 🏰 citadel, QA

#500 Add view control reference visual
  src/plugins/interactive_view_control/InteractiveViewControl.cc
Labels: 🏯 fortress

#501 Add pointer check in Application::RemovePlugin
  src/Application.cc
Labels: 🏰 citadel

#476 Added Reset button to world_control
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControlEventListener.cc
  src/plugins/world_control/WorldControlEventListener.hh
Labels: enhancement, 🌱 garden

#502 Fix large / unexpected camera movements
  src/plugins/interactive_view_control/InteractiveViewControl.cc
  src/plugins/minimal_scene/MinimalScene.cc
Labels: 🏯 fortress

#507 3.12.0 pre1
  CMakeLists.txt
Labels: 🏰 citadel

#508 3.12.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
