Repository gazebosim/gz-gui, pull requests merged in 2022-07, with the labels that each got.

#424 Add common widget for pose
  include/ignition/gui/qml/GzPose.qml
  include/ignition/gui/qml/IgnHelpers.qml
  include/ignition/gui/resources.qrc
Labels: 🏰 citadel, OOBE 📦✨

#431 Fix common widget Pose
  include/ignition/gui/qml/GzPose.qml
Labels: 🏰 citadel, OOBE 📦✨

#418 Allow Dialogs to have a MainWindow independent config
  include/ignition/gui/Application.hh
  include/ignition/gui/Dialog.hh
  include/ignition/gui/MainWindow.hh
  src/Application_TEST.cc
  src/CMakeLists.txt
  src/Dialog.cc
  src/Dialog_TEST.cc
Labels: 🏰 citadel, OOBE 📦✨

#427 Add common widget for vector3
  include/ignition/gui/qml/GzVector3.qml
  include/ignition/gui/resources.qrc
Labels: 🏰 citadel, OOBE 📦✨

#432 🎈 3.10.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#434 Forward-port 3 to 6
  .github/ci/after_make.sh
  Changelog.md
  examples/standalone/start_dialog/CMakeLists.txt
  examples/standalone/start_dialog/README.md
  examples/standalone/start_dialog/start_dialog.cc
  examples/standalone/start_dialog/start_dialog.qml
  examples/standalone/start_dialog/start_dialog.qrc
  include/ignition/gui/Application.hh
  include/ignition/gui/Dialog.hh
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/GzColor.qml
  include/ignition/gui/qml/GzPose.qml
  include/ignition/gui/qml/GzVector3.qml
  include/ignition/gui/qml/IgnHelpers.qml
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/CMakeLists.txt
  src/Dialog.cc
  src/Dialog_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/gui.bash_completion.sh
  src/ign_TEST.cc
  test/integration/minimal_scene.cc
Labels: 🏯 fortress

#435 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, QA

#436 3 ➡️ 6
  README.md
Labels: 🏯 fortress, QA

#438 Remove deprecated Scene3d plugin
  examples/standalone/scene_provider/README.md
  src/plugins/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/scene3d/Scene3D.qrc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/tape_measure/TapeMeasure.cc
  test/integration/scene3d.cc
Labels: 🌱 garden

#437 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  include/ignition/gui/config.hh.in
  include/ignition/gui/ign_auto_headers.hh.in
  include/ignition/gui/plugins/CMakeLists.txt
  tutorials.md.in
Labels: ign to gz

#430 Remove deprecated Image.Data API
  src/plugins/image_display/ImageDisplay.cc
Labels: bug, 🌱 garden

#441 Use stepping field in message
  src/plugins/world_control/WorldControl.cc
Labels: enhancement, 🌱 garden

#442 dialog config hotfix
  src/Dialog.cc
Labels: bug, 🏰 citadel

#444 Merge ign-gui2 ➡️ ign-gui3
  CMakeLists.txt
  api.md.in
  include/ignition/gui/config.hh.in
  include/ignition/gui/ign_auto_headers.hh.in
  tutorials.md.in
Labels: 🏰 citadel

#445 Merge ign-gui3 ➡️ ign-gui6
  CMakeLists.txt
  api.md.in
  include/ignition/gui/config.hh.in
  include/ignition/gui/ign_auto_headers.hh.in
  src/Dialog.cc
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop_TEST.cc
  tutorials.md.in
Labels: 🏯 fortress
