Repository gazebosim/gz-gui, pull requests merged in 2022-05, with the labels that each got.

#393 Add repo specific issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#386 Add config relative path environment variable
  src/Application.cc
  src/Application_TEST.cc
  src/cmd/cmdgui.rb.in
  tutorials/07_config.md
Labels: 🏰 citadel, OOBE 📦✨

#400 user camera FOV control in SDF files
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  test/integration/minimal_scene.cc
Labels: 🏯 fortress

#398 Update name and logo on UI, examples and API docs
  examples/README.md
  examples/config/plugin_params.config
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/HelloPlugin.hh
  examples/plugin/ign_components/README.md
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/custom_drawer/CustomDrawer.qml
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/marker/README.md
  examples/standalone/scene_provider/README.md
  examples/standalone/window/CMakeLists.txt
  include/gz/gui/Application.hh
  include/gz/gui/Conversions.hh
  include/gz/gui/Helpers.hh
  include/gz/gui/Plugin.hh
  include/gz/gui/config.hh.in
  include/gz/gui/qml/Main.qml
  include/gz/gui/qml/images/gazebo_logo.png
  include/gz/gui/qml/images/ignition_logo_50x50.png
  include/gz/gui/resources.qrc
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/images/ignition_logo_50x50.png
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/Conversions_TEST.cc
  src/MainWindow.cc
  src/cmd/cmdgui.rb.in
  src/plugins/CMakeLists.txt
  src/plugins/grid_config/GridConfig.hh
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/navsat_map/NavSatMap.hh
  src/plugins/navsat_map/NavSatMap.qml
  src/plugins/plotting/TransportPlotting.hh
  src/plugins/point_cloud/PointCloud.qml
  src/plugins/publisher/Publisher.hh
  src/plugins/scene3d/Scene3D.hh
  src/plugins/tape_measure/TapeMeasure.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/transport_scene_manager/TransportSceneManager.hh
Labels: 🌱 garden, ign to gz

#403 Search menu keyboard control
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🏯 fortress, OOBE 📦✨

#405 Shortcut to search and auto highlight search bar
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🏯 fortress, OOBE 📦✨

#408 Backport search menu updates from gui6 to gui3
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🏰 citadel

#406 ign -> gz Migrate Examples : gz-gui
  examples/plugin/gz_components/CMakeLists.txt
  examples/plugin/gz_components/GzComponents.cc
  examples/plugin/gz_components/GzComponents.config
  examples/plugin/gz_components/GzComponents.hh
  examples/plugin/gz_components/GzComponents.qml
  examples/plugin/gz_components/GzComponents.qrc
  examples/plugin/gz_components/README.md
  examples/plugin/ign_components/IgnComponents.config
  examples/plugin/ign_components/IgnComponents.qrc
Labels: 🌱 garden
