Repository gazebosim/gz-gui, pull requests merged in 2022-06, with the labels that each got.

#412 ign -> gz Environment Variable Migration : gz-gui
  src/MainWindow.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
Labels: 🌱 garden, ign to gz

#416 Disable failing test on Citadel
  src/ign_TEST.cc
Labels: 🏰 citadel, tests

#392 Bash completion for flags
  CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/gui.bash_completion.sh
  src/ign_TEST.cc
Labels: 🏰 citadel, needs upstream release, OOBE 📦✨

#419 Improve workflow tests robustness
  .github/ci/after_make.sh
Labels: 🏰 citadel

#420 Fix ign_TEST
  src/ign_TEST.cc
Labels: 🏰 citadel, tests, Windows

#417 ign -> gz CLI Migration : gz-gui
  CMakeLists.txt
  Changelog.md
  README.md
  conf/CMakeLists.txt
  examples/plugin/custom_context_menu/README.md
  examples/plugin/dialog_from_plugin/README.md
  examples/plugin/gz_components/README.md
  examples/plugin/hello_plugin/README.md
  examples/plugin/multiple_qml/README.md
  examples/standalone/marker/README.md
  examples/standalone/point_cloud/README.md
  examples/standalone/scene_provider/README.md
  include/gz/gui/CMakeLists.txt
  include/gz/gui/gz.hh
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdgui.rb.in
  src/gz.cc
  src/gz_TEST.cc
  src/plugins/interactive_view_control/InteractiveViewControl.hh
  tutorials.md.in
  tutorials/01_install.md
  tutorials/02_commandline.md
  tutorials/03_plugins.md
  tutorials/04_layout.md
  tutorials/05_style.md
  tutorials/06_example.md
  tutorials/07_config.md
  tutorials/08_screenshot.md
Labels: needs upstream release, 🌱 garden, ign to gz

#414 Rename CMake project to gz
  CMakeLists.txt
  doc/CMakeLists.txt
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/gz_components/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/point_cloud/CMakeLists.txt
  examples/standalone/scene_provider/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
  include/gz/gui/CMakeLists.txt
  src/CMakeLists.txt
  src/MainWindow.cc
  src/Plugin_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/camera_tracking/CMakeLists.txt
  src/plugins/grid_config/CMakeLists.txt
  src/plugins/image_display/CMakeLists.txt
  src/plugins/interactive_view_control/CMakeLists.txt
  src/plugins/marker_manager/CMakeLists.txt
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/point_cloud/CMakeLists.txt
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/scene3d/CMakeLists.txt
  src/plugins/screenshot/CMakeLists.txt
  src/plugins/screenshot/Screenshot.cc
  src/plugins/tape_measure/CMakeLists.txt
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/transport_scene_manager/CMakeLists.txt
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/CMakeLists.txt
  test/plugins/CMakeLists.txt
  tutorials/07_config.md
Labels: 🌱 garden, ign to gz

#410 Common widget GzColor (Citadel)
  include/ignition/gui/qml/GzColor.qml
  include/ignition/gui/resources.qrc
  src/plugins/grid_3d/Grid3D.qml
Labels: 🏰 citadel, OOBE 📦✨

#425 ign -> gz Partial Docs Migration and Project Name Followups : gz-gui
  CMakeLists.txt
  CONTRIBUTING.md
  Changelog.md
  Migration.md
  README.md
  api.md.in
  conf/gui.yaml.in
  include/gz/gui/GuiEvents.hh
  include/gz/gui/config.hh.in
  src/plugins/camera_tracking/CameraTracking.cc
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalSceneRhi.hh
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/tape_measure/TapeMeasure.hh
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/world_control/WorldControl.cc
  tutorials.md.in
  tutorials/01_install.md
  tutorials/index.md
  tutorials/scene.md
Labels: 🌱 garden

#428 Add .cc extension to suppress CMake warnings
  src/CMakeLists.txt
Labels: 🌱 garden

#407 Example running a dialog before the main window
  examples/standalone/start_dialog/CMakeLists.txt
  examples/standalone/start_dialog/README.md
  examples/standalone/start_dialog/start_dialog.cc
  examples/standalone/start_dialog/start_dialog.qml
  examples/standalone/start_dialog/start_dialog.qrc
  include/ignition/gui/Application.hh
  src/Application.cc
  src/Application_TEST.cc
Labels: 🏰 citadel, OOBE 📦✨
