Repository gazebosim/gz-gui, pull requests merged in 2022-04, with the labels that each got.

#381 Set cameraPassCountPerGpuFlush to 6
  src/plugins/minimal_scene/MinimalScene.cc
Labels: 🏯 fortress

#382 5 ➡️ 6
  Changelog.md
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/IgnSnackBar.qml
  include/ignition/gui/qml/IgnSplit.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.qml
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.qml
  src/plugins/teleop/Teleop.cc
Labels: 🏯 fortress

#383 6 ➡️ 7 (main)
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/IgnSnackBar.qml
  include/ignition/gui/qml/IgnSplit.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/MainWindow_TEST.cc
  src/plugins/camera_tracking/CameraTracking.hh
  src/plugins/camera_tracking/CameraTracking.qml
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/interactive_view_control/InteractiveViewControl.cc
  src/plugins/interactive_view_control/InteractiveViewControl.qml
  src/plugins/key_publisher/KeyPublisher.qml
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/marker_manager/MarkerManager.hh
  src/plugins/marker_manager/MarkerManager.qml
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalScene.qml
  src/plugins/minimal_scene/MinimalSceneRhi.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.mm
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.cc
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.hh
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.qml
  src/plugins/teleop/Teleop.cc
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/transport_scene_manager/TransportSceneManager.hh
  src/plugins/transport_scene_manager/TransportSceneManager.qml
  test/integration/minimal_scene.cc
  test/integration/transport_scene_manager.cc
Labels: 🌱 garden

#384 [ign to gz] Deprecate IGN_GUI_PLUGIN_PATH in favor of GZ_GUI_PLUGIN_PATH
  Migration.md
  examples/plugin/custom_context_menu/README.md
  examples/plugin/dialog_from_plugin/README.md
  examples/plugin/hello_plugin/README.md
  examples/plugin/ign_components/README.md
  examples/plugin/multiple_qml/README.md
  src/Application.cc
  tutorials/03_plugins.md
Labels: 🌱 garden, ign to gz

#385 Bumps in garden : ign-gui7
  .github/ci/packages.apt
  CMakeLists.txt
  src/Application_TEST.cc
  src/Helpers_TEST.cc
  src/MainWindow_TEST.cc
  src/PlottingInterface_TEST.cc
  src/Plugin_TEST.cc
  src/ign_TEST.cc
  src/plugins/plotting/TransportPlotting.hh
  src/plugins/point_cloud/PointCloud_TEST.cc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats_TEST.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
  test/integration/camera_tracking.cc
  test/integration/marker_manager.cc
  test/integration/minimal_scene.cc
  test/integration/scene3d.cc
  test/integration/transport_scene_manager.cc
Labels: 🌱 garden

#387 Sort plugin list in alphabetical order (including when filtering)
  include/ignition/gui/qml/PluginMenu.qml
Labels: 🏰 citadel, OOBE 📦✨

#388 Bumps in garden : ign-gui7
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden
