Repository gazebosim/gz-gui, pull requests merged in 2022-08, with the labels that each got.

#448 Fixed topic echo test
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho_TEST.cc
Labels: 🏰 citadel, tests, QA

#450 Dialog read attribute: don't create a file
  Migration.md
  include/ignition/gui/Dialog.hh
  src/Dialog.cc
  src/Dialog_TEST.cc
Labels: 🏰 citadel, OOBE 📦✨

#451 🎈 3.11.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#452 Merge ign-gui3 ➡️ ign-gui6
  Changelog.md
  Migration.md
  include/ignition/gui/Dialog.hh
  src/Dialog.cc
  src/Dialog_TEST.cc
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho_TEST.cc
Labels: 🏯 fortress

#453 🎈 6.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#446 Merge ign-gui6 ➡️ main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ci/after_make.sh
  CMakeLists.txt
  Changelog.md
  Migration.md
  examples/standalone/start_dialog/CMakeLists.txt
  examples/standalone/start_dialog/README.md
  examples/standalone/start_dialog/start_dialog.cc
  examples/standalone/start_dialog/start_dialog.qml
  examples/standalone/start_dialog/start_dialog.qrc
  include/gz/gui/Application.hh
  include/gz/gui/Dialog.hh
  include/gz/gui/qml/GzColor.qml
  include/gz/gui/qml/GzHelpers.qml
  include/gz/gui/qml/GzPose.qml
  include/gz/gui/qml/GzVector3.qml
  include/gz/gui/qml/Main.qml
  include/gz/gui/qml/PluginMenu.qml
  include/gz/gui/qml/qmldir
  include/gz/gui/qml/qmldir_deprecated
  include/gz/gui/resources.qrc
  src/Application.cc
  src/Application_TEST.cc
  src/CMakeLists.txt
  src/Dialog.cc
  src/Dialog_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdgui.rb.in
  src/cmd/gui.bash_completion.sh
  src/gz_TEST.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop.hh
  src/plugins/teleop/Teleop.qml
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_echo/CMakeLists.txt
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho.qml
  src/plugins/topic_echo/TopicEcho_TEST.cc
  test/integration/minimal_scene.cc
  tutorials/07_config.md
Labels: 🌱 garden

#447 Add test for Plugin::ConfigStr()
  src/Plugin.cc
  src/Plugin_TEST.cc
Labels: 🏰 citadel, tests

#439 Add plotting to common widget pose
  include/ignition/gui/qml/GzPlotIcon.qml
  include/ignition/gui/qml/GzPose.qml
  include/ignition/gui/qml/images/plottable_icon.svg
  include/ignition/gui/resources.qrc
Labels: enhancement, 🏯 fortress, OOBE 📦✨

#455 Fix attribute update when <dialog> isn't present
  include/ignition/gui/Dialog.hh
  src/Dialog.cc
  src/Dialog_TEST.cc
Labels: bug, 🏰 citadel, OOBE 📦✨, QA

#459 Fix main window moving with ColorDialogue of GzColor
  include/ignition/gui/qml/GzColor.qml
Labels: 🏰 citadel, OOBE 📦✨

#458 Merge ign-gui3 ➡️ ign-gui6
  include/ignition/gui/Dialog.hh
  include/ignition/gui/qml/GzColor.qml
  src/Dialog.cc
  src/Dialog_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
Labels: 🏯 fortress

#462 🎈 6.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#464 Fix warnings on Jammy
  src/CMakeLists.txt
  src/PlottingInterface_TEST.cc
Labels: bug, 🏯 fortress

#465 🏁 Update codeowners
  .github/CODEOWNERS
Labels: 🏰 citadel

#460 ign -> gz : Remove redundant namespace references
  examples/plugin/custom_context_menu/CustomContext.cc
  examples/plugin/dialog_from_plugin/DialogFromPlugin.cc
  examples/plugin/hello_plugin/HelloPlugin.cc
  examples/plugin/multiple_qml/MultipleQml.cc
  src/Application.cc
  src/Application_TEST.cc
  src/Conversions_TEST.cc
  src/DragDropModel_TEST.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/Plugin_TEST.cc
  src/SearchModel_TEST.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D_TEST.cc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/publisher/Publisher.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/teleop/Teleop.cc
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_viewer/TopicViewer.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
  test/plugins/TestBadInheritancePlugin.cc
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestPlugin.cc
Labels: 🏰 citadel, ign to gz

#461 Replace pose in Grid3d with GzPose
  src/plugins/grid_3d/Grid3D.qml
Labels: 🏰 citadel, OOBE 📦✨

#470 🎈 3.11.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#463 Replace color and pose for GridConfig with GzColor and GzPose
  src/plugins/grid_config/GridConfig.qml
Labels: 🏯 fortress, OOBE 📦✨

#472 Fix mistaken dialog error message
  src/Dialog.cc
Labels: bug

#471 Merge ign-gui3 ➡️ ign-gui6
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  examples/plugin/custom_context_menu/CustomContext.cc
  examples/plugin/dialog_from_plugin/DialogFromPlugin.cc
  examples/plugin/hello_plugin/HelloPlugin.cc
  examples/plugin/multiple_qml/MultipleQml.cc
  src/Application.cc
  src/Application_TEST.cc
  src/Dialog.cc
  src/DragDropModel_TEST.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/Plugin_TEST.cc
  src/SearchModel_TEST.cc
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.qml
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/publisher/Publisher.cc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/teleop/Teleop.cc
  src/plugins/topic_echo/TopicEcho.cc
  src/plugins/topic_viewer/TopicViewer.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_stats/WorldStats.cc
  test/integration/ExamplesBuild_TEST.cc
  test/integration/Examples_TEST.cc
  test/plugins/TestBadInheritancePlugin.cc
  test/plugins/TestInvalidQmlPlugin.cc
  test/plugins/TestPlugin.cc
Labels: 🏯 fortress

#474 🎈 3.11.2
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#475 Add degree as an optional unit for rotation in GzPose
  include/ignition/gui/qml/GzPose.qml
Labels: 🏰 citadel, OOBE 📦✨

#468 Fix image display test
  src/plugins/image_display/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/image_display/ImageDisplay_TEST.cc
Labels: 🏰 citadel, QA

#478 Update cmd/CMakeLists to conform with all other gz libraries
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdgui.rb.in
Labels: bug, 🏰 citadel

#479 Clean up library.hh headers
  include/gz/gui/Conversions.hh
  include/gz/gui/PlottingInterface.hh
  src/PlottingInterface_TEST.cc
  src/plugins/camera_tracking/CameraTracking.cc
  src/plugins/grid_config/GridConfig.cc
  src/plugins/grid_config/GridConfig.hh
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/interactive_view_control/InteractiveViewControl.cc
  src/plugins/key_publisher/KeyPublisher.cc
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/navsat_map/NavSatMap.hh
  src/plugins/point_cloud/PointCloud.hh
  src/plugins/publisher/Publisher.cc
  src/plugins/publisher/Publisher_TEST.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.hh
  src/plugins/screenshot/Screenshot_TEST.cc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/teleop/Teleop.cc
  src/plugins/teleop/Teleop_TEST.cc
  src/plugins/topic_echo/TopicEcho.hh
  src/plugins/topic_echo/TopicEcho_TEST.cc
  src/plugins/topic_viewer/TopicViewer.cc
  src/plugins/topic_viewer/TopicViewer_TEST.cc
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  test/integration/camera_tracking.cc
  test/integration/marker_manager.cc
  test/integration/transport_scene_manager.cc
Labels: bug, 🌱 garden
