Repository gazebosim/gz-gui, pull requests merged in 2022-09, with the labels that each got.

#480 Update cmd/CMakeLists to conform with all other gz libraries (#478)
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdgui.rb.in
Labels: bug, 🌱 garden

#469 Fix crash at exit of gz-sim by using RTLD_NODELETE=true when loading libraries
  src/Application.cc
Labels: bug, 🌱 garden, Breaking change

#490 Remove unused headers
  include/gz/gui/gz_auto_headers.hh.in
  include/ignition/gui/ign_auto_headers.hh
Labels: bug, 🌱 garden

#486 Add missing headers
  examples/standalone/point_cloud/point_cloud.cc
Labels: bug, 🌱 garden

#492 Update changelog for 7.0.0
  Changelog.md
Labels: 🌱 garden
