Repository gazebosim/gz-gui, pull requests merged in 2022-01, with the labels that each got.

#342 NavSat (GPS) map plugin
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  src/plugins/CMakeLists.txt
  src/plugins/navsat_map/CMakeLists.txt
  src/plugins/navsat_map/NavSatMap.cc
  src/plugins/navsat_map/NavSatMap.hh
  src/plugins/navsat_map/NavSatMap.qml
  src/plugins/navsat_map/NavSatMap.qrc
Labels: enhancement, 🏯 fortress

#344 🎈 6.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#345 Add project() to examples and remove hard-dependency on Ogre1
  CMakeLists.txt
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
Labels: 🏰 citadel

#347 Prevent Scene3D 💥 if another scene is already loaded
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  test/integration/scene3d.cc
Labels: bug, 🏰 citadel, OOBE 📦✨

#348 3 ➡️ 5
  CMakeLists.txt
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  test/integration/scene3d.cc
Labels: 🏢 edifice

#335 Added a button that allows shutting down both the client and server.
  examples/config/dialog_on_exit_shutdown.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/shutdown_button/CMakeLists.txt
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/shutdown_button/ShutdownButton.hh
  src/plugins/shutdown_button/ShutdownButton.qml
  src/plugins/shutdown_button/ShutdownButton.qrc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/shutdown_button/test.config
  test/config/close_dialog_auto_gui_only.config
  test/config/close_dialog_auto_shutdown.config
  test/config/close_dialog_buttons.config
  test/config/close_dialog_buttons_text.config
  test/config/close_dialog_custom_shutdown_service.config
  test/config/close_dialog_default_buttons.config
  tutorials/04_layout.md
Labels: 🏰 citadel

#350 🎈 3.9.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#349 Improve inserting WorldControl and WorldStats from menu
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats_TEST.cc
Labels: bug, 🏰 citadel, OOBE 📦✨

#351 3 ➡️ 5
  Changelog.md
  examples/config/dialog_on_exit_shutdown.config
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/shutdown_button/CMakeLists.txt
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/shutdown_button/ShutdownButton.hh
  src/plugins/shutdown_button/ShutdownButton.qml
  src/plugins/shutdown_button/ShutdownButton.qrc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/shutdown_button/test.config
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats_TEST.cc
  test/config/close_dialog_auto_gui_only.config
  test/config/close_dialog_auto_shutdown.config
  test/config/close_dialog_buttons.config
  test/config/close_dialog_buttons_text.config
  test/config/close_dialog_custom_shutdown_service.config
  test/config/close_dialog_default_buttons.config
  tutorials/04_layout.md
Labels: 🏢 edifice

#346 Point cloud visualization plugin
  examples/standalone/point_cloud/CMakeLists.txt
  examples/standalone/point_cloud/README.md
  examples/standalone/point_cloud/point_cloud.cc
  examples/standalone/point_cloud/point_cloud.config
  include/ignition/gui/Helpers.hh
  src/Helpers_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/point_cloud/CMakeLists.txt
  src/plugins/point_cloud/PointCloud.cc
  src/plugins/point_cloud/PointCloud.hh
  src/plugins/point_cloud/PointCloud.qml
  src/plugins/point_cloud/PointCloud.qrc
  src/plugins/point_cloud/PointCloud_TEST.cc
Labels: 🌱 garden

#352 5 ➡️ 6
  CMakeLists.txt
  Changelog.md
  examples/config/dialog_on_exit_shutdown.config
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_provider/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/shutdown_button/CMakeLists.txt
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/shutdown_button/ShutdownButton.hh
  src/plugins/shutdown_button/ShutdownButton.qml
  src/plugins/shutdown_button/ShutdownButton.qrc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/shutdown_button/test.config
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats_TEST.cc
  test/config/close_dialog_auto_gui_only.config
  test/config/close_dialog_auto_shutdown.config
  test/config/close_dialog_buttons.config
  test/config/close_dialog_buttons_text.config
  test/config/close_dialog_custom_shutdown_service.config
  test/config/close_dialog_default_buttons.config
  test/integration/scene3d.cc
  tutorials/04_layout.md
Labels: 🏯 fortress

#353 6 ➡️ 7 (main)
  .github/ci/packages.apt
  CMakeLists.txt
  Changelog.md
  Migration.md
  examples/config/dialog_on_exit_shutdown.config
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/ign_components/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_provider/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/Main.qml
  src/Application.cc
  src/MainWindow.cc
  src/MainWindow_TEST.cc
  src/plugins/CMakeLists.txt
  src/plugins/navsat_map/CMakeLists.txt
  src/plugins/navsat_map/NavSatMap.cc
  src/plugins/navsat_map/NavSatMap.hh
  src/plugins/navsat_map/NavSatMap.qml
  src/plugins/navsat_map/NavSatMap.qrc
  src/plugins/scene3d/Scene3D.cc
  src/plugins/scene3d/Scene3D.hh
  src/plugins/scene3d/Scene3D.qml
  src/plugins/shutdown_button/CMakeLists.txt
  src/plugins/shutdown_button/ShutdownButton.cc
  src/plugins/shutdown_button/ShutdownButton.hh
  src/plugins/shutdown_button/ShutdownButton.qml
  src/plugins/shutdown_button/ShutdownButton.qrc
  src/plugins/shutdown_button/ShutdownButton_TEST.cc
  src/plugins/shutdown_button/test.config
  src/plugins/world_control/WorldControl.cc
  src/plugins/world_control/WorldControl.hh
  src/plugins/world_control/WorldControl.qml
  src/plugins/world_control/WorldControl_TEST.cc
  src/plugins/world_stats/WorldStats.cc
  src/plugins/world_stats/WorldStats.hh
  src/plugins/world_stats/WorldStats.qml
  src/plugins/world_stats/WorldStats_TEST.cc
  test/config/close_dialog_auto_gui_only.config
  test/config/close_dialog_auto_shutdown.config
  test/config/close_dialog_buttons.config
  test/config/close_dialog_buttons_text.config
  test/config/close_dialog_custom_shutdown_service.config
  test/config/close_dialog_default_buttons.config
  test/integration/scene3d.cc
  tutorials/04_layout.md
Labels: 🌱 garden
