Repository gazebosim/gz-gui, pull requests merged in 2022-03, with the labels that each got.

#359 Removed unused code in MinimalScene plugin
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
Labels: 🏯 fortress

#362 Improve KeyPublisher's usability
  src/plugins/key_publisher/KeyPublisher.qml
Labels: 🏰 citadel, OOBE 📦✨

#364 Prevent MinimalScene 💥 if another scene is already loaded
  src/Application.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalScene.qml
Labels: 🏯 fortress, OOBE 📦✨

#366 Populate plugins that were empty
  src/plugins/camera_tracking/CameraTracking.hh
  src/plugins/camera_tracking/CameraTracking.qml
  src/plugins/interactive_view_control/InteractiveViewControl.cc
  src/plugins/interactive_view_control/InteractiveViewControl.qml
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/marker_manager/MarkerManager.hh
  src/plugins/marker_manager/MarkerManager.qml
Labels: 🏯 fortress, OOBE 📦✨

#365 TransportSceneManager: Prevent freeze when inserted from menu
  src/plugins/transport_scene_manager/TransportSceneManager.cc
  src/plugins/transport_scene_manager/TransportSceneManager.hh
  src/plugins/transport_scene_manager/TransportSceneManager.qml
  test/integration/transport_scene_manager.cc
Labels: 🏯 fortress, OOBE 📦✨

#323 Add Metal support to MinimalScene and Qt Application
  src/Application.cc
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalSceneRhi.cc
  src/plugins/minimal_scene/MinimalSceneRhi.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.mm
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.cc
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.hh
Labels: macOS, 🌱 garden

#368 Fix menu scrolling when a new plugin is added
  include/ignition/gui/qml/IgnSplit.qml
Labels: 🏰 citadel, OOBE 📦✨

#369 Added Snackbar qtquick object
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/IgnSnackBar.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/resources.qrc
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.qml
  src/plugins/teleop/Teleop.cc
Labels: 🏰 citadel, OOBE 📦✨

#372 Use ign-rendering's screenToScene functions
  src/plugins/minimal_scene/MinimalScene.cc
Labels: bug, 🏯 fortress, MBARI-LRAUV

#371 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  tutorials/01_install.md
Labels: documentation, tests, 🌱 garden

#373 Fix nondiscard warnings with lock_guard
  src/plugins/point_cloud/PointCloud.cc
Labels: bug, Windows, 🌱 garden

#376 Fix some Qt warnings
  src/Application.cc
  src/plugins/world_control/WorldControl.qml
Labels: 🏰 citadel

#370 Added array to snackbar qml
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/IgnSnackBar.qml
  include/ignition/gui/qml/Main.qml
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/screenshot/Screenshot.cc
  src/plugins/teleop/Teleop.cc
Labels: 🏰 citadel, OOBE 📦✨

#377 3 ➡️ 5
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/qml/IgnSnackBar.qml
  include/ignition/gui/qml/IgnSplit.qml
  include/ignition/gui/qml/Main.qml
  include/ignition/gui/resources.qrc
  src/Application.cc
  src/plugins/grid_3d/Grid3D.cc
  src/plugins/grid_3d/Grid3D.hh
  src/plugins/grid_3d/Grid3D.qml
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/key_publisher/KeyPublisher.qml
  src/plugins/screenshot/Screenshot.cc
  src/plugins/screenshot/Screenshot.qml
  src/plugins/teleop/Teleop.cc
Labels: 🏢 edifice

#378 🎈🏁 5.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#380 Avoid nullptr access in MinimalScene
  src/plugins/minimal_scene/MinimalScene.cc
Labels: bug, 🏯 fortress

#374 Add Ubuntu Jammy CI
  .github/workflows/ci.yml
  src/Helpers_TEST.cc
  src/MainWindow_TEST.cc
  test/integration/minimal_scene.cc
  test/integration/transport_scene_manager.cc
Labels: 🏯 fortress
