Repository gazebosim/gz-gui, pull requests merged in 2022-12, with the labels that each got.

#506 Set View Camera controller from plugin configuration
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  test/integration/minimal_scene.cc
Labels: 🏯 fortress

#509 🎈 6.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#505 Change reset button position
  src/plugins/world_control/WorldControl.qml
Labels: needs upstream release, 🌱 garden

#357 Add fallback rendering for other APIs
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/EngineToQtInterface.cc
  src/plugins/minimal_scene/EngineToQtInterface.hh
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  src/plugins/minimal_scene/MinimalSceneRhi.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.hh
  src/plugins/minimal_scene/MinimalSceneRhiMetal.mm
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.cc
  src/plugins/minimal_scene/MinimalSceneRhiOpenGL.hh
Labels: bug, 🌱 garden
