Repository gazebosim/gz-gui, pull requests merged in 2023-03, with the labels that each got.

#522 🎈 7.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#521 Update maintainer email
  README.md
Labels: 🏰 citadel

#523 Add Camera FPS plugin
  src/plugins/CMakeLists.txt
  src/plugins/camera_fps/CMakeLists.txt
  src/plugins/camera_fps/CameraFps.cc
  src/plugins/camera_fps/CameraFps.hh
  src/plugins/camera_fps/CameraFps.qml
  src/plugins/camera_fps/CameraFps.qrc
Labels: 🏯 fortress

#525 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#526 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#524 6 ➡️ 7
  src/plugins/CMakeLists.txt
  src/plugins/camera_fps/CMakeLists.txt
  src/plugins/camera_fps/CameraFps.cc
  src/plugins/camera_fps/CameraFps.hh
  src/plugins/camera_fps/CameraFps.qml
  src/plugins/camera_fps/CameraFps.qrc
  test/integration/camera_tracking.cc
Labels: 🌱 garden

#527 Merge 3 -> 6 (part 1)
  Changelog.md
  conf/CMakeLists.txt
  include/ignition/gui/qml/GzPose.qml
  src/Application.cc
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdgui.rb.in
  src/plugins/image_display/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/image_display/ImageDisplay.hh
  src/plugins/image_display/ImageDisplay.qml
  src/plugins/image_display/ImageDisplay_TEST.cc
  src/plugins/key_publisher/CMakeLists.txt
  src/plugins/key_publisher/KeyPublisher.hh
  src/plugins/key_publisher/KeyPublisher_TEST.cc
Labels: 🏯 fortress
