Repository gazebosim/gz-gui, pull requests merged in 2023-06, with the labels that each got.

#543 Fix TopicInfo deprecation warnings
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/navsat_map/NavSatMap.cc
  src/plugins/point_cloud/PointCloud.cc
  src/plugins/topic_viewer/TopicViewer.cc
Labels: 🎵 harmonic

#544 Protobuf: Do not require version 3 do support Protobuf 4.23.2 (23.2)
  CMakeLists.txt
Labels: 🏯 fortress

#547 Backport #544: Find any major version of Protobuf
  CMakeLists.txt
Labels: 🏰 citadel

#550 Merge ign-gui6 ➡️ gz-gui7
  CMakeLists.txt
  Changelog.md
  src/plugins/camera_tracking/CameraTracking.cc
Labels: 🌱 garden

#551 Merge gz-gui7 ➡️ main
  CMakeLists.txt
  Changelog.md
  src/plugins/camera_tracking/CameraTracking.cc
Labels: 🎵 harmonic
