Repository gazebosim/gz-gui, pull requests merged in 2023-04, with the labels that each got.

#454 ign -> gz Migrate config and log directories : gz-gui
  src/Application.cc
  tutorials/02_commandline.md
  tutorials/03_plugins.md
  tutorials/05_style.md
  tutorials/06_example.md
  tutorials/08_screenshot.md
Labels: 🌱 garden, ign to gz

#530 Disable Teleop_TEST on macOS
  src/plugins/teleop/Teleop_TEST.cc
Labels: 🌱 garden

#529 Apply low-pass filter to RTF display
  src/plugins/world_stats/WorldStats.cc
Labels: 🌱 garden

#534 Disable deprecation messages about onFoo connections
  src/Application.cc
Labels: 🌱 garden

#536 CI workflow: use checkout v3 (jammy)
  .github/workflows/ci.yml
Labels: 🏯 fortress

#537 Fix data race issues in CameraTracking plugin
  src/plugins/camera_tracking/CameraTracking.cc
Labels: 🏯 fortress

#528 Add support for bayer images to get displayed in gazebo gui
  src/plugins/image_display/ImageDisplay.cc
Labels: 🌱 garden
