Repository gazebosim/gz-gui, pull requests merged in 2023-11, with the labels that each got.

#591 Update github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#567 Fix plugin filter on Windows
  include/gz/gui/CMakeLists.txt
  src/Application.cc
  src/MainWindow.cc
Labels: 🌱 garden

#597 Update Github Action workflows
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#599 Merge ign-gui3 ➡️ ign-gui6
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏯 fortress
