Repository gazebosim/gz-gui, pull requests merged in 2023-09, with the labels that each got.

#569 Update README.md
  README.md
Labels: 🎵 harmonic

#570 Changes ignition for gz in tutorial commands
  tutorials/01_install.md
Labels: bug, 🎵 harmonic

#571 Add plugins namespace
  include/gz/gui/Plugin.hh
Labels: beta, 🎵 harmonic

#574 Fix crash when starting Topic Viewer
  src/plugins/topic_viewer/TopicViewer.cc
Labels: beta, 🎵 harmonic

#575 Use fully-qualified message names to avoid deprecation warning
  src/plugins/topic_viewer/TopicViewer.cc
Labels: beta, 🎵 harmonic

#576 Prepare for 7.2.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#577 Merge: 7 -> 8
  Changelog.md
Labels: 🎵 harmonic

#578 Prepare for 8.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#579 Prepare for 8.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
