Repository gazebosim/gz-gui, pull requests merged in 2023-08, with the labels that each got.

#559 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#560 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#531 WorldControl: use event by default
  src/plugins/world_control/WorldControl.cc
Labels: beta, 🎵 harmonic

#429 Fix segfaulting tests
  src/Helpers_TEST.cc
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  test/helpers/RenderEngineHelper.hh
  test/integration/camera_tracking.cc
  test/integration/marker_manager.cc
  test/integration/minimal_scene.cc
  test/integration/transport_scene_manager.cc
Labels: bug, tests, beta, 🌱 garden

#563 Make plugins include message types they use
  src/plugins/camera_tracking/CameraTracking.cc
  src/plugins/point_cloud/PointCloud.cc
Labels: 🎵 harmonic

#564 Port: 7 to main
  .github/workflows/triage.yml
  src/Helpers_TEST.cc
  src/plugins/minimal_scene/CMakeLists.txt
  src/plugins/minimal_scene/MinimalScene.cc
  test/helpers/RenderEngineHelper.hh
  test/integration/camera_tracking.cc
  test/integration/marker_manager.cc
  test/integration/minimal_scene.cc
  test/integration/transport_scene_manager.cc
Labels: 🎵 harmonic

#566 Fix issue in TopicViewer
  src/plugins/topic_viewer/TopicViewer.cc
Labels: beta, 🎵 harmonic

#556 Remove ignition
  examples/plugin/gz_components/GzComponents.qml
  include/CMakeLists.txt
  include/gz/gui/gz.hh
  include/gz/gui/qml/qmldir
  include/gz/gui/qml/qmldir_deprecated
  include/gz/gui/resources.qrc
  include/ignition/gui.hh
  include/ignition/gui/Application.hh
  include/ignition/gui/Conversions.hh
  include/ignition/gui/Dialog.hh
  include/ignition/gui/DragDropModel.hh
  include/ignition/gui/Enums.hh
  include/ignition/gui/Export.hh
  include/ignition/gui/GuiEvents.hh
  include/ignition/gui/Helpers.hh
  include/ignition/gui/MainWindow.hh
  include/ignition/gui/PlottingInterface.hh
  include/ignition/gui/Plugin.hh
  include/ignition/gui/SearchModel.hh
  include/ignition/gui/config.hh
  include/ignition/gui/ign.hh
  include/ignition/gui/qt.h
  src/Application.cc
  src/MainWindow.cc
  src/Plugin.cc
  src/gz.cc
  src/plugins/marker_manager/MarkerManager.cc
  src/plugins/minimal_scene/MinimalScene.cc
  test/integration/deprecated_TEST.cc
Labels: beta, 🎵 harmonic
