Repository gazebosim/gz-gui, pull requests merged in 2024-01, with the labels that each got.

#604 Merge 6 ➡️ 7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  src/plugins/image_display/ImageDisplay.cc
Labels: 🌱 garden, 🎵 harmonic

#605 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#606 Merge 7 ➡️ 8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  src/plugins/image_display/ImageDisplay.cc
Labels: 🎵 harmonic
