Repository gazebosim/gz-gui, pull requests merged in 2024-08, with the labels that each got.

#632 Merge gz-gui8 ➡️ main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  .github/workflows/package_xml.yml
  Changelog.md
  conf/CMakeLists.txt
  doc/CMakeLists.txt
  examples/standalone/scene_provider/README.md
  include/gz/gui/CMakeLists.txt
  include/gz/gui/qml/Main.qml
  include/gz/gui/qml/images/drawer_dark.png
  include/gz/gui/qml/images/menu_dark.png
  include/gz/gui/resources.qrc
  package.xml
  src/Application.cc
  src/MainWindow.cc
  src/cmd/CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/camera_tracking/CameraTracking.cc
  src/plugins/camera_tracking/CameraTracking.hh
  src/plugins/camera_tracking/CameraTracking.qml
  src/plugins/camera_tracking_config/CMakeLists.txt
  src/plugins/camera_tracking_config/CameraTrackingConfig.cc
  src/plugins/camera_tracking_config/CameraTrackingConfig.hh
  src/plugins/camera_tracking_config/CameraTrackingConfig.qml
  src/plugins/camera_tracking_config/CameraTrackingConfig.qrc
  src/plugins/grid_config/CMakeLists.txt
  src/plugins/image_display/ImageDisplay.cc
  src/plugins/minimal_scene/EngineToQtInterface.cc
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.qml
Labels: beta, 🏛️ ionic

#634 Enable ubuntu noble on github actions, require cmake 3.22.1
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  examples/plugin/custom_context_menu/CMakeLists.txt
  examples/plugin/dialog_from_plugin/CMakeLists.txt
  examples/plugin/gz_components/CMakeLists.txt
  examples/plugin/hello_plugin/CMakeLists.txt
  examples/plugin/multiple_qml/CMakeLists.txt
  examples/standalone/custom_drawer/CMakeLists.txt
  examples/standalone/dialogs/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/point_cloud/CMakeLists.txt
  examples/standalone/scene_provider/CMakeLists.txt
  examples/standalone/start_dialog/CMakeLists.txt
  examples/standalone/window/CMakeLists.txt
Labels: 🏛️ ionic

#633 Expose shadow texture size for directional lighting in SDF
  src/plugins/minimal_scene/MinimalScene.cc
  src/plugins/minimal_scene/MinimalScene.hh
  test/integration/minimal_scene.cc
Labels: beta, 🏛️ ionic

#635 Ionic changelog
  Changelog.md
Labels: 🎵 harmonic

#636 Update badges for ionic gz-gui9
  README.md
Labels: 🏛️ ionic

#631 Add a flexible mechanism to combine user and default plugins
  include/gz/gui/Application.hh
  src/Application.cc
Labels: beta, Breaking change, 🏛️ ionic

#637 Prepare for 9.0.0~pre1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic
